version: '{build}'
image: Visual Studio 2017
environment:
  WORKSPACE: %APPVEYOR_BUILD_FOLDER%
install:
  - cmd: .\.ci\windows\install
# build_script:
#   - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
#   - cmd: .\.ci\windows\build
# test_script:
#   - cmd: .\.ci\windows\post_build
