.build_template: &build_template
  variables:
    WORKSPACE: $CI_PROJECT_DIR
  before_script:
    - ./.ci/deb/install
  script:
    - ./.ci/deb/build
  after_script:
    - ./.ci/deb/post_build

pages:
  image: debian:stretch
  script:
    - apt-get update
    - apt-get install -y mkdocs
    - mkdocs build -d ../public -f ./mkdocs.yml
    - mv ../public ./
  artifacts:
    paths:
      - public
    only:
    - master


build_stretch:
  <<: *build_template
  image: debian:stretch
