.build_template: &build_template
  before_script:
    - ./.ci/deb/install
  script:
    - ./.ci/deb/build
  after_script:
    - ls -l
    - ./.ci/deb/post_build

pages:
  image: debian:stretch
  variables:
    LC_ALL: C.UTF-8
    LANG: C.UTF-8
  script:
    - apt-get update
    - apt-get install -y python3-pip
    - pip3 install mkdocs
    - mkdocs build -d public
  artifacts:
    paths:
      - public
  only:
    - master

build_stretch:
  <<: *build_template
  variables:
    WORKSPACE: $CI_PROJECT_DIR
    BUILD_DIR: build.stretch
    INSTALL_DIR: install.stretch
  image: debian:stretch

build_bionic:
  <<: *build_template
  variables:
    WORKSPACE: $CI_PROJECT_DIR
    BUILD_DIR: build.bionic
    INSTALL_DIR: install.bionic
  image: ubuntu:bionic
