.build_template: &build_template
  stage: build
  variables:
    WORKSPACE: $CI_PROJECT_DIR
  script:
    - ./.ci/deb/install
    - ./.ci/deb/build
    - ./.ci/deb/post_build

pages:
  stage: deploy
  image: debian:stretch
  variables:
    LC_ALL: C.UTF-8
    LANG: C.UTF-8
  script:
    - apt-get update
    - apt-get install -y python3-pip
    - pip3 install mkdocs
    - mkdocs build -d public
  artifacts:
    paths:
      - public
  only:
    - master

build_stretch:
  extends: .build_template
  image: debian:stretch
  # Check the code samples in the documentation
  after_script:
    - apt-get update
    - apt-get install -y python3-bs4 python3-markdown
    - python3 docs/check_code_samples.py build/

build_bionic:
  extends: .build_template
  image: ubuntu:bionic
