site_name: Sycomore
repo_url: https://git.unistra.fr/lamy/sycomore/
site_author: Julien Lamy
site_description: Sycomore - an MRI simulation toolkit
nav:
  - Home: index.md
  - User Guide:
    - installation.md
    - units.md
    - species.md
    - pulses.md
    - time_intervals.md
    - models.md
  - About: []
theme: 
  name: readthedocs
markdown_extensions:
  - toc:
      permalink: true
